### ISSUE TITLE
what does the dxfv::s_dxf_draw used for?

### ISSUE THREAD

**Issue by asmwarrior** [JamesBremner/DXF_Viewer#1]
Hi, your source code builds OK under Code::Blocks in my Windows 7.

I see your original post is here: [Simple DXF Reader/Viewer with Spline Support - CodeProject by ravenspoint](https://www.codeproject.com/Tips/786156/Simple-DXF-Reader-Viewer-with-Spline-Support-2)

My question is: What is the variable: dxfv::s_dxf_draw used for, I see that all the element drawing is using this variable.
From the original code I see from: [Simple DXF Reader/Viewer with Spline Support - CodeProject by Hasan Gurler](https://www.codeproject.com/Tips/652988/Simple-DXF-Reader-Viewer-with-Spline-Support), I don't see it use such a variable. Each elements has its own way to draw on the device context.

**Comment by JamesBremner** [comment]
Thank you for your interest in my code.

> source code builds OK under Code::Blocks in my Windows 7.

Congratulations.  That must have been a challenge.  I have added a codeblocks project to build, which should make this easier in future.

> What is the variable: dxfv::s_dxf_draw used fo

`dxfv::s_dxf_draw `is NOT a variable.  It is a structure.  The declaration of the structure is in `Dxf.h` and is documented there.

https://github.com/JamesBremner/DXF_Viewer/blob/0181b13cf0960e3b95b7532d34464259ad4b3349/src/Dxf.h#L180-L201

**Comment by asmwarrior** [comment]
I'm one of the Code::Block's developer. 
Using your code is quite simple, I just create a simple wx application by the project wizard under Code::Blocks, and then I remove the code in the project, and add all your source code to the project, then it just build fine.

**Comment by JamesBremner** [comment]
Can this issue be closed?

**Comment by asmwarrior** [comment]
Yes, I think this issue can be closed. Thanks.
