### ISSUE TITLE
crash when loading test file dxf/polyline.dxf

### ISSUE THREAD

**Issue by asmwarrior** [JamesBremner/DXF_Viewer#11]
Hi, when loading the test file:  dxf/polyline.dxf
I see a crash happens at here:

```
class cCodeValue
{
public:
    std::string myCode;
    std::string myValue;

    bool Read( std::ifstream& f )
    {
        if( ! std::getline(f, myCode) )
            return false;
        if( ! std::getline(f, myValue) )
            return false;
        // remove leading whitespace from the group code
        size_t p = myCode.find_first_not_of(" ");
        if( p > 0 )
            myCode.erase(0,p-1);
        return true;
    }
    int Code()
    {
        return atoi( myCode.c_str() );
    }
};
```
I see that the myCode string is empty.
I'm testing on the latest commit:  [Fix CLine::getDraw](https://github.com/JamesBremner/DXF_Viewer/commit/bdd3f3ea99b6c862891c707246180fa974801be8)

**Comment by JamesBremner** [comment]
Not reproducible.

![image](https://user-images.githubusercontent.com/2046227/62909489-d2994380-bd4a-11e9-9352-7891d54de4a5.png)

**Comment by asmwarrior** [comment]
I debugged for a while, and the crash issue comes from the invalid iterator.

Here in the code snippet:
```
bool cLWPolyLine::Append(  cvit_t& cvit )
{
    int point_index = 0;
    while( true )
    {
        cvit++;
        switch( cvit->Code() )
        {
        case 0:
            // a new object
            cvit--;
            return false;
        case 8:
            m_Layer = cvit->myCode;
            break;
        case 90:
            m_VertexCount = atoi(cvit->myValue.c_str());
            break;
        case 70:
            myfClosed = atoi(cvit->myValue.c_str());
            break;
        case 10:
            x[point_index] = atof(cvit->myValue.c_str());
            break;
        case 20:
            y[point_index++] = atof(cvit->myValue.c_str());
            break;
        }
    }
    return true;
}
```
When you run the `cvit++;` statement, the iterator increased. But this time, it just reaches the end of the container. So, the iterator becomes invalid.

I found this crash issue happens after reading the last pair of the code:
```
 20
630.7866032049806
```
Note, the above two line are the last two lines of the file dxf/polyline.dxf.  At this time, the loop just continues to append the points, but it looks like it has no way to check when the iterator becomes the `container.end()`.

My guess is that either the dxf file has missing some ending text lines, or the code need to be improved to determine a correct end of the iterator.

**Comment by JamesBremner** [comment]
Please remember to assign issues to me!

**Comment by asmwarrior** [comment]
Tested, and there is no crash now. Thanks, I close this issue.
