### ISSUE TITLE
Support splines with mixed fit and control points

### ISSUE THREAD

**Issue by asmwarrior** [JamesBremner/DXF_Viewer#13]
[sample_dxf.zip](https://github.com/JamesBremner/DXF_Viewer/files/3495892/sample_dxf.zip)
I get an C++ exception when I load a sample dxf file, which contains such contents.

```
SPLINE
  5
7E
330
1F
100
AcDbEntity
  8
kalem
100
AcDbSpline
210
0.0
220
0.0
230
1.0
 70
     8
 71
     3
 72
    14
 73
    10
 74
     8
 42
0.0000000001
 43
0.0000000001
 44
0.0
```
The full dxf file comes from the Hasan Gurler's CodeProject post: [Simple DXF Reader/Viewer with Spline Support - CodeProject](https://www.codeproject.com/Tips/652988/Simple-DXF-Reader-Viewer-with-Spline-Support), in his attachment code achieve, this is one only test dxf file `\DXF Reader\dxf\sample.dxf`

In our code, I see that 73 and 74 are numbers for control points and fit points, in our code, it is not allowed for both control points and fit points.
```
 73
    10
 74
     8
```
So, I believe our code can't parse the AcDbSpline class?

Thanks.

EDIT: I have added the sample dxf file.

**Comment by asmwarrior** [comment]
I read the document page from here: [AcDbSpline | Search | Autodesk Knowledge Network](https://knowledge.autodesk.com/search-result/caas/CloudHelp/cloudhelp/2017/ENU/OARXMAC-RefGuide/files/OREFMAC-AcDbSpline-html.html), there, it said:

> Objects of the AcDbSpline class use an embedded gelib object to maintain the actual spline information. The spline itself may either be a simple curve fit (within a specified tolerance which may be 0) through a set of "fit points," or it may be a NURBS spline (that is, a set of control points, knots, and weights used to define the spline path). **Internally, a curve-fit spline still has NURBS data; however the reverse is not true.** 

The last sentence is the cause of this issue?

**Comment by JamesBremner** [comment]
> I get an C++ exception when I load a sample dxf file, which contains such contents.

Please retest.  You should get an informative message pop up, followed by program termination when the message is acknowledged.  If this does not happen, open a bug issue.

Note that the sample DXF file you posted above will not load because it is improperly opened and terminated

```
0
ENTITIES
...
0
EOF
```

**Comment by JamesBremner** [comment]
Note that supporting splines with mixed fit and control points will wait until pure control point splines are working ( #2 ).  NURBS support will wait even longer.

**Comment by JamesBremner** [comment]
I have added the ENTITIES section to your sample file.  It now works properly (i.e. detects the problem. informs the user before exiting gracefully )

![image](https://user-images.githubusercontent.com/2046227/62938027-2bdd9300-bd9c-11e9-8f60-4ee35355d1d3.png)

**Comment by asmwarrior** [comment]
OK, so no crash of the program, and it exits after the message box. 
I think this issue can becomes a feature request? Since I see in this page: https://github.com/JamesBremner/DXF_Viewer/blob/master/README.md  It will be a "todo list".

> SPLINE with fit AND control points

**Comment by JamesBremner** [comment]
> Splines are defined either with fit points, or with control vertices. 

from https://knowledge.autodesk.com/support/autocad/learn-explore/caas/CloudHelp/cloudhelp/2016/ENU/AutoCAD-Core/files/GUID-5E7D51E2-1595-4E0C-85F8-2D7CBD166A08-htm.html

I think that it makes no sense to draw a spline with both fit points AND splines.  It is an either-or situation.

Perhaps the sample DXF files that define both fit and control points in the same spline entity must be an error, or perhaps they offer both and the viewer can use whichever one set of points is preferred.

So, I can add a configuration setting that will select one set of point for drawing in the case where both control and fit points are present in an entity.  Let me know if you want this.  Otherwise I do not think there is anything to do here.

Note also, from the same source:

> SPLINE creates curves called nonuniform rational B-splines (NURBS), referred to as splines for simplicity.

So, SPLINE and NURBS are synonymous.  I will remove NURBS from the list of unsupported entities.

**Comment by asmwarrior** [comment]
> I think that it makes no sense to draw a spline with both fit points AND splines. It is an either-or situation.

Yes. I agree.

> Perhaps the sample DXF files that define both fit and control points in the same spline entity must be an error, or perhaps they offer both and the viewer can use whichever one set of points is preferred.

I see such DXF files many times. Those files are from difference sources. I mainly guess it is not a DXF file error, maybe like you said "they offer both and the viewer can use whichever one set of points is preferred". Anyway, I'm not an AutoCAD export.

> So, I can add a configuration setting that will select one set of point for drawing in the case where both control and fit points are present in an entity. Let me know if you want this. 

Yes, I totally agree your option. Thanks.

**Comment by JamesBremner** [comment]
To change the preferred points, edit this line and rebuild

https://github.com/JamesBremner/DXF_Viewer/blob/32af5af555ebedc6d614356b41e32ed6a93a4362/src/Dxf.cpp#L128

**Comment by asmwarrior** [comment]
Hi, James, thanks for your work!
I just tested it with either myfSplineControlPointsPreferred set as `true` or `false`, all works fine. 
So, I think this issue can be closed.
