### ISSUE TITLE
dxfv::CSolid::Draw(dxfv::CDxf*) is missing for the wxWidgets target

### ISSUE THREAD

**Issue by asmwarrior** [JamesBremner/DXF_Viewer#19]
Hi, I see that CSolid::Draw is only implemented in the src/windex.cpp, not in src/wxWidgets.cpp.
This causes a link error when building the wxWidgets target.

**Comment by JamesBremner** [comment]
You are correct.  I do not use wxWidgets anymore.

**Comment by asmwarrior** [comment]
A good candidate for drawing the solid under wxWidgets is using this function: [DrawPolygon](https://docs.wxwidgets.org/3.0.4/classwx_d_c.html#a86e50a20fa6b634b9ce590ce8a900e1c), I will see if I have time to implement the missing future in the next days.

**Comment by asmwarrior** [comment]
[implement void CSolid::Draw( CDxf* dxf ) for wxWidgets target](https://github.com/JamesBremner/DXF_Viewer/pull/27/commits/9ebddb3109713bf55ed54b7a2b2b0e42624193db)

This implement the wxWidgets target for the SOLID.

**Comment by JamesBremner** [comment]
Can this be closed now?

**Comment by asmwarrior** [comment]
Yes, we can close it.
