### ISSUE TITLE
Add support for drawing spline line with control points

### ISSUE THREAD

**Issue by asmwarrior** [JamesBremner/DXF_Viewer#2]
Hi, from your source code, I see you just skip the spline with control points. You only support the spline with fitpoints. So, my question is: can you support the spline with control points.

Under wxWidgets, I see there is a function named: DrawSpline, which you only need to supply all the points of the spline, you can have a look at this sample code from: [Device contexts in wxWidgets](http://zetcode.com/gui/wxwidgets/gdi/), the last image of this page shows a spline.

Any suggestions?
Thanks.

**Comment by JamesBremner** [comment]
The documentation for the wxWidgets DrawSpline method ( https://docs.wxwidgets.org/3.0/classwx_d_c.html#ad72d38c75ac6b3f80c1f957dd94089fa ) says:

> Draws a spline between all given points using the current pen.

This suggests to me that it uses fit points.  What makes you think it uses control points?  Have you tried it?

**Comment by asmwarrior** [comment]
Hi, I already tested it by using the code snippet(the last code snippet in that web page) I mentioned in my first post: [Device contexts in wxWidgets](http://zetcode.com/gui/wxwidgets/gdi/)

```
    dc.DrawSpline(4, splines);
    dc.SetPen(wxPen(*wxBLUE, 5, wxSOLID));
    for (int i = 0; i<4; i++)
    {
        dc.DrawLine(splines[i].x, splines[i].y,splines[i].x, splines[i].y);
    }
```
You can see the spline is not go through the second and third points. So, my conclution is that the wxWidgets' DrawSpline method is using the control point.

**Comment by asmwarrior** [comment]
Oh, I just notice that you have pushed new code [Display control point splines as simplified "linear" Beziers](https://github.com/JamesBremner/DXF_Viewer/commit/2a49776616a102f236f6b6543d9620f8ffb74e79) to implement this feature.

**Comment by asmwarrior** [comment]
Tested, and it works fine! Great!
I think this issue(feature request) is implemented. Thanks.
