### ISSUE TITLE
different interpretation of the start and end angle?

### ISSUE THREAD

**Issue by xubury** [JamesBremner/DXF_Viewer#21]
I did a hand calculation on your last comment on https://github.com/JamesBremner/DXF_Viewer/pull/17. I didn't see anything wrong with the x1 x2 y1 y2 output, but I can't understand the quadrant you described. 
I follow your interpretation on https://github.com/JamesBremner/DXF_Viewer/blob/master/src/Arc.h#L10-L17.
With sa 5 and ea 85, isn't it at top right quadrant like the first screenshot?
With sa 375 and ea 355, doesn't the arc cover the every quadrant like the second screenshot?
![QQ截图20200312215353](https://user-images.githubusercontent.com/46261364/76528643-1f452880-64ac-11ea-99ed-afba1743fd6c.png)
![QQ截图20200312215403](https://user-images.githubusercontent.com/46261364/76528651-21a78280-64ac-11ea-85ec-930a93782c40.png)

**Comment by JamesBremner** [comment]
You are correct!
