### ISSUE TITLE
Support B-Splines ( Bezier curve with knots )

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/DXF_Viewer#29]
Reported in #28 by @asmwarrior 

For this test file [test-spline.zip](https://github.com/JamesBremner/DXF_Viewer/files/15412058/test-spline.zip)

**Comment by JamesBremner** [comment]
It looks to me like the problem is with the control points.  They cover a miniscule region

```
 10
24725.95168097708
 20
-6770.748197816759
 30
0.0
 10
24725.85852500357
 20
-6770.744391059349
 30
0.0
 10
24725.67366692644
 20
-6770.737364052635
 30
0.0
 10
24725.40059914378
 20
-6770.728504625802
 30
0.0
 10
24725.22134645974
 20
-6770.723671547369
 30
0.0
 10
24725.08797355941
 20
-6770.720432330077
 30
0.0
 10
24725.04369397797
 20
-6770.719416863622
 30
0.0
 10
24724.97754681914
 20
-6770.717988001715
 30
0.0
 10
24724.9555155109
 20
-6770.717526896118
 30
0.0
 10
24724.91174060111
 20
-6770.71663967941
 30
0.0
 10
24724.80296704548
 20
-6770.714507762875
 30
0.0
 10
24724.61306549609
 20
-6770.711419207895
 30
0.0
 10
24724.37212535598
 20
-6770.708703301245
 30
0.0
 10
24724.21968042127
 20
-6770.707708348229
 30
0.0
 10
24724.10849739111
 20
-6770.707225482587
 30
0.0
 10
24724.07190893277
 20
-6770.707108381802
 30
0.0
 10
24724.00018885624
 20
-6770.706955572835
 30
0.0
 10
24723.96503322469
 20
-6770.706919622963
 30
0.0
 10
24723.93058293476
 20
-6770.706919622963
 30
```

**Comment by JamesBremner** [comment]
If I suppress all other graphical objects except the spline and zoom in, the display is

![image](https://github.com/JamesBremner/DXF_Viewer/assets/2046227/0b67737f-bb1b-4c40-b4a9-4cd080981922)


So, it is NOT a matter of layers.

The problem is with the control points.  There are only 19 of them and thay cover a miniscule region, relative to the other objects in the file.  Also 19 control points is not nearly enough to generate the complex curve that you are expecting.

I notice that your file specifies that the spline has 23 'knots'.  Perhaps that is what generating the curve you are expecting?  This view does not support knots.

**Comment by JamesBremner** [comment]
If you want me to try to implement spline knots I will need a much simpler test file - with no other objects than the spline and with just two or three knots.  Please include a display of the expected curve.

**Comment by JamesBremner** [comment]
A spline specification with both control points and knots is called a B-Spline.  Spline with control points only is a Bezier curve.  https://mathworld.wolfram.com/B-Spline.html

B-Splines are not supported and will now raise an exception

**Comment by asmwarrior** [comment]
Thanks for the explanation. In-fact, I'm not quite familiar with so many kinds of those splines. I will try to make a minimal B-spline dxf file today.

**Comment by asmwarrior** [comment]
[test-spline-try-1.zip](https://github.com/JamesBremner/DXF_Viewer/files/15433570/test-spline-try-1.zip)


I try to upload a simple spline dxf file, and when I open it in the liberCAD, it looks like below:

![image](https://github.com/JamesBremner/DXF_Viewer/assets/561818/be9ded0f-ac36-4ea1-bb1c-ec1a4160f0d7)

And when I use the DXF_Viewer, it looks like below:

![image](https://github.com/JamesBremner/DXF_Viewer/assets/561818/a15d31a0-2271-4193-9b27-3f0bb0d4fd59)

Hope this is the spline file you need for testing. Thanks.

**Comment by JamesBremner** [comment]
Your test file has over 5,000 lines of meaningless content.  I have committed a filtered version https://github.com/JamesBremner/DXF_Viewer/blob/master/dxf/bsplinetid29-1.dxf

**Comment by JamesBremner** [comment]
According to this ( https://mathworld.wolfram.com/B-Spline.html ) the knot values should be in the range 0 to 1 inclusive.

According to this ( https://help.autodesk.com/view/OARX/2023/ENU/?guid=GUID-E1F884F8-AA90-4864-A215-3182D47A9C74 ) the knot code is 40.

Here is that section of your test file

```
 40
0
 40
0
 40
0
 40
0
 40
102.418326765
 40
172.406544897
 40
268.623648794
 40
362.130518826
 40
454.882895757
 40
545.400596524
 40
545.400596524
 40
545.400596524
 40
545.400596524
```

I will normalise these values by dividing them all by the last knot value

**Comment by asmwarrior** [comment]
Thanks for your effert.

When I opened my dxf file in LibreCAD, I see there are many of control points, see the image below(I mark them as red circle), but I can't found the knot points. My guess is that LibreCAD does not handle this format very well.

![image](https://github.com/JamesBremner/DXF_Viewer/assets/561818/263e1ccb-018c-402f-b74d-98ec83d6854f)

**Comment by JamesBremner** [comment]
I have implemented the B-Spline algorithm ( https://mathworld.wolfram.com/B-Spline.html )

I have not committed the code because it does not generate the same display as you posted https://github.com/JamesBremner/DXF_Viewer/issues/29#issuecomment-2129304167

I assumed that this was because of a bug in my implementation, although I have been unable to find it by stepping through the code with a debugger and other methods.  The algorithm is fairly complex, so a hard to find bug is to be expected.

Now, with https://github.com/JamesBremner/DXF_Viewer/issues/29#issuecomment-2130661324 it seems that you have low confidence that the display you posted is correct.

Can you provide a small, simple DXF file that contains a B-Spline along with a generated curve that you are confident is correct.  Ideally I would like to see the x,y values of the curve so that I can do numerical testing rather than just comparing displays.

**Comment by asmwarrior** [comment]
> I have implemented the B-Spline algorithm ( https://mathworld.wolfram.com/B-Spline.html )
> 
> I have not committed the code because it does not generate the same display as you posted [#29 (comment)](https://github.com/JamesBremner/DXF_Viewer/issues/29#issuecomment-2129304167)
> 
> I assumed that this was because of a bug in my implementation, although I have been unable to find it by stepping through the code with a debugger and other methods. The algorithm is fairly complex, so a hard to find bug is to be expected.
> 
> Now, with [#29 (comment)](https://github.com/JamesBremner/DXF_Viewer/issues/29#issuecomment-2130661324) it seems that you have low confidence that the display you posted is correct.
> 
> Can you provide a small, simple DXF file that contains a B-Spline along with a generated curve that you are confident is correct. Ideally I would like to see the x,y values of the curve so that I can do numerical testing rather than just comparing displays.

Thanks.

I have download another tool named QCAD, and I open the file: test-spline-try-1.dxf

It looks like QCAD reported that this file, the spline only has control points, so no knot points in this spline.

In-fact, I see in QCAD, it can only create a spline which has all control points, or a spline which has all knot points. I really don't know how to create a "B spline" which has both kinds of two points.

**Comment by JamesBremner** [comment]
> It looks like QCAD reported that this file, the spline only has control points, so no knot points in this spline.

Here are the knots in that file

![image](https://github.com/JamesBremner/DXF_Viewer/assets/2046227/cf8e06e4-68a8-45a8-a344-35296e52d88d)

**Comment by JamesBremner** [comment]
> or a spline which has all knot points.

A spline with no knot points is meaningless.

A spline with control points only generates a Bezier Curve.

A spline with control points AND knots generates a special kind of Bezier curve, which is called a B-Spline.

Please read https://mathworld.wolfram.com/B-Spline.html

**Comment by JamesBremner** [comment]
> I really don't know how to create a "B spline"

Which makes me wonder why you want this feature in DXF_Viewer.

**Comment by asmwarrior** [comment]
> > I really don't know how to create a "B spline"
> 
> Which makes me wonder why you want this feature in DXF_Viewer.

The reason is that some of my clients will send me the dxf file. The dxf file were exported from some software such as AutoCAD or Solidworks. In the past, when I try to import the dxf file, it will always failed. I suspect the "DXF_Viewer" can't handle such kinds of dxf(either the exception dialog will jump out or the loaded graphics ware not fully shown), so I asked them to convert all the splines to polylines, and export the dxf again. Thus, the dxf  can be loaded and shown correctly by the "DXF_Viewer".


> > or a spline which has all knot points.
> 
> A spline with no knot points is meaningless.
> 
> A spline with control points only generates a Bezier Curve.
> 
> A spline with control points AND knots generates a special kind of Bezier curve, which is called a B-Spline.
> 
> Please read https://mathworld.wolfram.com/B-Spline.html

Yes, I read this, I just need to find a way myself to generate the B-Spline. So I have installed some tool like "LiberCAD" or "QCAD", but sadly, I don't know how to add control points or knots in those tools.

**Comment by asmwarrior** [comment]
I read more document about B spline, see here:

Cubic B Splines Introduction and Description - YouTube — https://www.youtube.com/watch?v=anK2Eka2K-Y

This video tutorial is nice.

Also, the wikipedia page:

9 Cubic B-Splines — https://en.wikipedia.org/wiki/B-spline#Cubic_B-Splines

From the text data you extracted, I see the data is exactly the Cubic B-Spline.

The first 4 knots are all `0`, which means the curve is from the P0(the first control point), and the last 4 knots are all "1"(normalized value, they are `545.400596524` in the dxf file).

**Comment by asmwarrior** [comment]
> Thanks for your effert.
> 
> When I opened my dxf file in LibreCAD, I see there are many of control points, see the image below(I mark them as red circle), but I can't found the knot points. My guess is that LibreCAD does not handle this format very well.
> 
> ![image](https://private-user-images.githubusercontent.com/561818/333762133-263e1ccb-018c-402f-b74d-98ec83d6854f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2OTAwMDYsIm5iZiI6MTcxNjY4OTcwNiwicGF0aCI6Ii81NjE4MTgvMzMzNzYyMTMzLTI2M2UxY2NiLTAxOGMtNDAyZi1iNzRkLTk4ZWM4M2Q2ODU0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQwMjE1MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOGZlMGVmM2U3ZGNlY2E2MzI0NzY4MWQyZDBiMjUwNzc0ZWNmMTAzNDc5ZTczNDE0NjYxY2JmY2JhY2UyZjNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GueXn3xppYUuwCQ4GoxmpnCWNHbm1EX0jcZmhX6yQsM)

I think the above image shows correctly, those points marked as "circle" are all control points.

**Comment by asmwarrior** [comment]
refer to the document here: https://ocw.snu.ac.kr/sites/default/files/NOTE/223.pdf, it is a pdf tutorial about B spline. 

It looks like some times, for knots, its value is not normalized, it just from 0 to a 4 (in the pdf page 21).

**Comment by asmwarrior** [comment]
I try to use the QCAD to create another dxf file, which contains a B-Spline, see below:

![image](https://github.com/JamesBremner/DXF_Viewer/assets/561818/ef6d6579-1a7a-4d77-83cc-2da023191de7)

The dxf file has the format: Format: R27 [2013] DXF Drawing [OpenDesign] (*.dxf)

[spline-from-qcad.zip](https://github.com/JamesBremner/DXF_Viewer/files/15446904/spline-from-qcad.zip)

It is still a very large dxf file, but by searching the keyword "40", I see the knots are round the line 

~~~
SPLINE
  5
3D
330
5B
100
AcDbEntity
  8
0
100
AcDbSpline
210
0.0
220
0.0
230
1.0
 70
     8
 71
     3
 72
    15
 73
    11
 74
     0
 42
0.000000001
 43
0.001
 40
0.0
 40
0.0
 40
0.0
 40
0.0
 40
1.0
 40
2.0
 40
3.0
 40
4.0
 40
5.0
 40
6.0
 40
7.0
 40
8.0
 40
8.0
 40
8.0
 40
8.0
~~~

**Comment by asmwarrior** [comment]
I have duplicated the B-Spline, and later convert the second B-Spline to polyline. See the attached zip file

[spline-from-qcad-with-polyline.zip](https://github.com/JamesBremner/DXF_Viewer/files/15447467/spline-from-qcad-with-polyline.zip)

See the image below:

![image](https://github.com/JamesBremner/DXF_Viewer/assets/561818/9f786fb0-8f0a-4938-aa72-9825bf291569)

When you search the dxf file, you will see some lines like:

~~~
AcDbPolyline
 90
       78
 70
   128
 43
0.0
 10
5.000000000000028
 20
26.99999999999973
 42
0.0143544023651
 10
5.082936804082244
 20
24.1116974103607
 42
0.0217654017319864
 10
5.27501212030711
 20
22.21525283800348
 42
0.0248729059774672
 10
5.552067636227212
 20
20.80656070148991
 42
0.0373001244074611
...
...
~~~

Which is the polyline definition.

**Comment by JamesBremner** [comment]
I have taken the file you posted in https://github.com/JamesBremner/DXF_Viewer/issues/29#issuecomment-2132151066, renamed it and added it to the repo.

My code makes some sense of this file, except for some severe end effects.  This screen shows the central 60% of the curve generated

![image](https://github.com/JamesBremner/DXF_Viewer/assets/2046227/c38402d0-da0d-4bcd-be7b-99d51a84e1bd)

Next week I will work on fixing the end effects.

**Comment by asmwarrior** [comment]
> Next week I will work on fixing the end effects.

Good work, thanks, hope you will success next week. The recursive definition of bspline make the code complex.

**Comment by asmwarrior** [comment]
I try to find how the spline is drawn in the wxWidgets framework, and finally I see a function:

https://github.com/wxWidgets/wxWidgets/blob/67951782cbe5aadada6c4389097b2387ab88d920/src/msw/dc.cpp#L1258

It looks like [PolyBezier function (wingdi.h) - Win32 apps | Microsoft Learn](https://learn.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-polybezier) function is used. It just need the control points, the end points. The start point is optional. Also, I guess that the "end point" can be calculated by the knot values.

**Comment by JamesBremner** [comment]
> I try to find how the spline is drawn

There are different kinds of spline

A Bezier spline is a curve specified by control points.

A B-spline is a curve specified by control points AND knots.

The wingdi function you found handles Bezier splines, but not B-splines.

DXF-Viewer has an implementation of Bezier curves that works well.  Test with sample file `splineCP.dxf`

DXF-Viewer lacks an implementation of B-Splines.  That is what this issue is about.  That is what I am working on.

**Comment by asmwarrior** [comment]
> > I try to find how the spline is drawn
> 
> There are different kinds of spline
> 
> A Bezier spline is a curve specified by control points.
> 
> A B-spline is a curve specified by control points AND knots.
> 
> The wingdi function you found handles Bezier splines, but not B-splines.
> 
> DXF-Viewer has an implementation of Bezier curves that works well. Test with sample file `splineCP.dxf`
> 
> DXF-Viewer lacks an implementation of B-Splines. That is what this issue is about. That is what I am working on.

OK, thanks for the explanation.

**Comment by JamesBremner** [comment]
Your test spline bsplinetid29-2.dxf is clamped - the curve start and ends on a control point.  For details of clamping see https://pages.mtu.edu/~shene/COURSES/cs3621/NOTES/spline/B-spline/bspline-curve.html

My code, despite working on all day, does not handle clamped splines.  

Do you any interest in a solution for unclamped splines?

**Comment by asmwarrior** [comment]
> Your test spline bsplinetid29-2.dxf is clamped - the curve start and ends on a control point. For details of clamping see https://pages.mtu.edu/~shene/COURSES/cs3621/NOTES/spline/B-spline/bspline-curve.html

I read this page, I think this web page explains better than the https://mathworld.wolfram.com/B-Spline.html

> 
> My code, despite working on all day, does not handle clamped splines.
> 
> Do you any interest in a solution for unclamped splines?

In my simple test, I create b-spline from QCAD, or I have asked my client to create a b-spline from AutoCAD, it looks like these lines are "clamped splines".

So, my answer to your question is: let only handle the "clamped splines" first. (If I see some unclamped splines in the generated dxf files from those software tool, I can file another issue)

Well, in the page, it said:

> To do so, the first knot and the last knot must be of multiplicity p+1. This will generate the so-called clamped B-spline curves. 

This means some duplicated knot points happens, such as `0,0,0,0` in the attached example dxf files.
I'm not sure the "clamped or unclamped" splines can be handled in a unified method. Since those four `0` means a “vanished” spline segment.
Thanks.

**Comment by JamesBremner** [comment]
> let only handle the "clamped splines" first. 

Clamped splines are the ones that I am failing to handle

So I asked:  "Do you have any interest in a solution for unclamped splines?"

Yes or No answer only, please.

**Comment by asmwarrior** [comment]
> > let only handle the "clamped splines" first.
> 
> Clamped splines are the ones that I am failing to handle
> 
> So I asked: "Do you have any interest in a solution for unclamped splines?"
> 
> Yes or No answer only, please.

No.

**Comment by JamesBremner** [comment]
OK.

I will commit my current code to its own development branch, for unclamped B-Splines

I will open a new issue for unclamped B-Splines

I will open a new issue for clamped B-Splines

I will close this issue

**Comment by asmwarrior** [comment]
OK, thanks, I can do more test on different dxf files from my clients.

**Comment by JamesBremner** [comment]
Finally got some code that produces a reasonable display

![image](https://github.com/JamesBremner/DXF_Viewer/assets/2046227/8a7ef7ed-0d3a-4990-a832-9ed797847f2f)

**Comment by asmwarrior** [comment]
> Finally got some code that produces a reasonable display
> 
> ![image](https://private-user-images.githubusercontent.com/2046227/335224778-8a7ef7ed-0d3a-4990-a832-9ed797847f2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNzk4NjEsIm5iZiI6MTcxNzA3OTU2MSwicGF0aCI6Ii8yMDQ2MjI3LzMzNTIyNDc3OC04YTdlZjdlZC0wZDNhLTQ5OTAtYTgzMi05ZWQ3OTc4NDdmMmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MzBUMTQzMjQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmQ1MGMwNWMyMTliNWNhMmFhNmNhMjFhNTViNTkzNWMxNDA0OTgxZmVlYTVjNDc0NWM0NTVkMTdkZjM2ZWZjNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.uBK6qlmRVBud52jhI0bkqDkbS6FMvzU1JTd5DEbDy9k)

Nice work!

**Comment by JamesBremner** [comment]
Please test with release v1.1.0

**Comment by asmwarrior** [comment]
> Your test file has over 5,000 lines of meaningless content. I have committed a filtered version https://github.com/JamesBremner/DXF_Viewer/blob/master/dxf/bsplinetid29-1.dxf

Hi, James, thanks for your work!

I'm testing this dxf file with the latest git head code. I just download this dxf file, and I failed to open this file in LibreCAD, it said import error. See below:

![image](https://github.com/JamesBremner/DXF_Viewer/assets/561818/17b46f9b-58b7-4b26-9159-ad38a2086aaf)

This dxf file also can't opened by the DXF_Viewer, see image below:
![image](https://github.com/JamesBremner/DXF_Viewer/assets/561818/653e7dd8-021e-40e9-ab6a-fb271b609ae8)

So, I guess that some text line is wrong in the dxf file.

Here is the result I test other dxf files:

I try to test the old unmodified dxf file https://github.com/JamesBremner/DXF_Viewer/files/15433570/test-spline-try-1.zip

I see that DXF_Viewer can view the dxf file correctly, see below:

![image](https://github.com/JamesBremner/DXF_Viewer/assets/561818/cc96059d-9ce1-401b-9513-afc63ff300f3)

For another dxf file:  https://github.com/JamesBremner/DXF_Viewer/files/15446904/spline-from-qcad.zip

It works correctly, see below:

![image](https://github.com/JamesBremner/DXF_Viewer/assets/561818/24b4da58-fdb6-47da-9cd9-1af61d023de2)

As a conclusion, It works OK.

I will test other dxf files in the future. Thanks.

**Comment by JamesBremner** [comment]
> As a conclusion, It works OK.
