### ISSUE TITLE
Draw closed polyline

### ISSUE THREAD

**Issue by asmwarrior** [JamesBremner/DXF_Viewer#3]
Hi, I see currently, the code does not draw closed polyline.
For a reference, [POLYLINE (DXF) | Search | Autodesk Knowledge Network](https://knowledge.autodesk.com/search-result/caas/CloudHelp/cloudhelp/2017/ENU/AutoCAD-DXF/files/GUID-ABF6B778-BE20-4B49-9B58-A94E64CEFFF3-htm.html), which says that for a default polyline, the group code 70 = 0, while for group code 70 = 1, we can simply connect the first point and last point, thus make a closed polyline.

```
    for( dxfv::CPolyLine& polyline : dxf->m_PolyLine )
    {
        dxf->Init( draw );
        while( polyline.getDraw( draw ) )
        {
            dc.DrawLine( draw.x1, draw.y1, draw.x2, draw.y2 );
        }
    }
```
This code may be updated with some if condition for the m_PolyLineFlag field check.

Thanks.

**Comment by asmwarrior** [comment]
This is a bug in the latest git head which cause endless loop when drawing closed polyline:

```
bool CPolyLine::getDraw( s_dxf_draw& draw )
{
    if( 0 > draw.index || draw.index == (int)m_VertexCount )
        return false;
    if( draw.index == (int)m_VertexCount  )
        return false;
    if( draw.index == (int)m_VertexCount-1  )
    {
        if( ! myfClosed )
        {
            return false;
        }
        else
        {
            draw.x1 = x[draw.index];
            draw.y1 = y[draw.index];
            draw.x2 = x[0];
            draw.y2 = y[0];
        }
    }
    else
    {
        draw.x1 = x[draw.index];
        draw.y1 = y[draw.index];
        draw.index++;
        draw.x2 = x[draw.index];
        draw.y2 = y[draw.index];
    }
    draw.rect->ApplyScale( draw.x1, draw.y1 );
    draw.rect->ApplyScale( draw.x2, draw.y2 );

    return true;
}

```

I think the index should be increased in this brace:
```
        {
            draw.x1 = x[draw.index];
            draw.y1 = y[draw.index];
            draw.x2 = x[0];
            draw.y2 = y[0];
        }
```

**Comment by JamesBremner** [comment]
Fixed.  ( I would assign the issue back to you for testing, but you forgot to assign it to me. )

**Comment by asmwarrior** [comment]
It works OK now, so I think this issue can be closed, thanks!
