### ISSUE TITLE
Display empty circles

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/DXF_Viewer#31]
Requested in #30 
> when drawing the "circle", do we need to fill the circle? Because sometimes, the user only need to draw the circle lines.

**Comment by JamesBremner** [comment]
The DXF standard does not have a group code for empty or filled circles.

https://help.autodesk.com/view/OARX/2023/ENU/?guid=GUID-8663262B-222C-414D-B133-4A8506A27C18

Options:

1. Change parsing of code 39 ( thickness ) so that 9001 means empty circle of thickness 1, 9002 empty circle of thickness 2.

 Assumes thickness > 9000 never used.   you will need to modify your DXF file generator.

2. For an empty circle use an arc of 359 degrees.  For this you will need to modify your DXF file generator.  No change to this repo

3. Modify `CCircle::Draw()` to draw an empty circle.  This will change _every_ circle to empty.

**Comment by JamesBremner** [comment]
@asmwarrior This question is for you.

**Comment by JamesBremner** [comment]
Since there _is_ a thickness code, it only makes sense that circles are expected to be empty.

**Comment by JamesBremner** [comment]
For your wxWidgets code you will need to set the brush to the BLACK_BRUSH standard object since the circle is drawn with the current pen and filled with the current brush.

**Comment by JamesBremner** [comment]
@asmwarrior this should be assigned to you ( you need to post to an issue before I can assign it to you. )

**Comment by asmwarrior** [comment]
From what I searched from the internet, it looks like the circle object in DXF should not be filled.

So, the brush should be empty, I don't think the black brush is needed.

I will test it myself right now.

**Comment by asmwarrior** [comment]
![image](https://github.com/user-attachments/assets/67dedf01-38b4-472a-943b-fd05968774e7)

I finally to use the transparent brush, so both the circle and arc is not filled, see the image above, I will write another pull request soon for the wxWidgets port.

**Comment by asmwarrior** [comment]
[wxWidgets gui drawing adjusts: both the circle and arc should not be … by asmwarrior · Pull Request #33 · JamesBremner/DXF_Viewer](https://github.com/JamesBremner/DXF_Viewer/pull/33)

This is my new PR
