### ISSUE TITLE
Limit GUI framework dependencies to one file

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/DXF_Viewer#35]
Almost all GUI framework library dependent code is limited to one source file ( windex.cpp or wxWidgets.cpp ).

There remain a few dependencies in dxf.h.  If these were removed then dxf.h could be significantly simplified and maintenance eased.

**Comment by JamesBremner** [comment]
@asmwarrior Would you be interested in removing the wxWidgets dependencies from dxf.h?

If you do that, I will remove all support for nana ( I do not believe anyone uses nana ) and the source code will no longer be marred by conditional compiles.

**Comment by asmwarrior** [comment]
> @asmwarrior Would you be interested in removing the wxWidgets dependencies from dxf.h?
> 
> If you do that, I will remove all support for nana ( I do not believe anyone uses nana ) and the source code will no longer be marred by conditional compiles.

I will look at it in the next few days.

About the nana gui framework, I haven't used it before, but when I looked at its github repo, it looks like the nana gui framework's code base does not update for about 3 or 4 years. So, it is dead?

**Comment by JamesBremner** [comment]
I would not be surprised if nana was dead.  I gave up using nana several years ago, partly because maintenance was so poor - my pull requests to fix bugs were ignored.

> I will look at it

Great.  I will assign this issue to you.

**Comment by JamesBremner** [comment]
Your pull requests are merged.

I will now drop nana support.

**Comment by JamesBremner** [comment]
Nana gone, except for some codeblocks projects.  https://github.com/JamesBremner/DXF_Viewer/commit/926086718473d7a89325f86cddeee63e4d55bf88

All conditional compiles gone from dxf.h, along with dead and unused code.  I have also moved some type specific code to the source files that implement the types.

The code in dxf.h should now be more comprehensible and maintainable.
