### ISSUE TITLE
Consistent case for *.h filenames

### ISSUE THREAD

**Issue by asmwarrior** [JamesBremner/DXF_Viewer#39]
https://github.com/JamesBremner/DXF_Viewer/blob/8a7a31a3db4b5b3e59bbde3e282b77d2c39d5251/src/Arc.cpp#L8

I think the code should be:

~~~
#include "Dxf.h"
~~~

Because we have a file named: `src/Dxf.h`.

I see there are many cpp files which use the "dxf.h", so they should be fixed.

**Comment by asmwarrior** [comment]
Another issue is:

In the file: `Dimension.cpp`, it use the code:

~~~
#include "stdafx.h"
#include "DXF.h"
~~~

I think the first file should be "StdAfx.h", but does this file needed. It is a file back in MFC framework many years ago under MSVC compiler.

The second file should be "Dxf.h".

**Comment by asmwarrior** [comment]
I added the fix commit in my PR #38

**Comment by JamesBremner** [comment]
You are aware the filenames are case insensitive in windows OS?

While these changes are harmless, they are just churn.

**Comment by JamesBremner** [comment]
Merged.

**Comment by asmwarrior** [comment]
> You are aware the filenames are case insensitive in windows OS?
> 

Yes, I know, but maybe someday, this library will be used under Linux or Mac.

**Comment by JamesBremner** [comment]
I used to care about that, and tried to make sure everything was "cross platform" as far as possible.  A waste of effort.
