### ISSUE TITLE
 zoom in/out around the mouse pointer

### ISSUE THREAD

**Issue by asmwarrior** [JamesBremner/DXF_Viewer#4]
Hi, as the title said, I think when user zoom the dxf file, the elements under the mouse pointer should not be changed. 

In the wxWidgets‘ forum, there is a nice implementation about this feature in this discussion: [Re: How to Zoom ?](https://forums.wxwidgets.org/viewtopic.php?f=1&t=43595#p178016), there [doublemax](https://forums.wxwidgets.org/memberlist.php?mode=viewprofile&u=3397) gives us a minimal sample code to demonstrate this. I hope this feature can also put in the DXF_Viewer. 

Thanks.

**Comment by JamesBremner** [comment]
To zoom into a particular feature:

- Using mouse with left button down, drag feature of interest to center of display window
- Zoom in

( This is how zooming is done in google maps )

**Comment by asmwarrior** [comment]
> 
> 
> To zoom into a particular feature:
> 
>     * Using mouse with left button down, drag feature of interest to center of display window
> 
>     * Zoom in
> 
> 
> ( This is how zooming is done in google maps )
OK, I just test it, and it works fine as the way google maps.

But I still suggest adding the zoom around the cursor, or can we add an option to the zoom feature, such that one choice is zoom around the window center, another choice is zoom around the mouse cursor(I see a lot of CAD or circuit schematic drawing program works like this).

Thanks.

**Comment by JamesBremner** [comment]
>But I still suggest adding the zoom around the cursor, 

I will not implement this,

> OK, I just test it, and it works fine as the way google maps.

Closing
