### ISSUE TITLE
Which DXF file versions are supported?

### ISSUE THREAD

**Issue by asmwarrior** [JamesBremner/DXF_Viewer#42]
Hi, I just want to know, the current DXF_Viewer will support which version of the DXF file format.

I just found in the autodesk document, it has such content:

[Drawing format version codes for AutoCAD](https://www.autodesk.com/support/technical/article/caas/sfdcarticles/sfdcarticles/drawing-version-codes-for-autocad.html)
~~~
MC0.0 - DWG Release 1.1
AC1.2 - DWG Release 1.2
AC1.4 - DWG Release 1.4
AC1.50 - DWG Release 2.0
AC2.10 - DWG Release 2.10
AC1002 - DWG Release 2.5
AC1003 - DWG Release 2.6
AC1004 - DWG Release 9
AC1006 - DWG Release 10
AC1009 - DWG Release 11/12 (LT R1/R2)
AC1012 - DWG Release 13 (LT95)
AC1014 - DWG Release 14, 14.01 (LT97/LT98)
AC1015 - DWG AutoCAD 2000/2000i/2002
AC1018 - DWG AutoCAD 2004/2005/2006
AC1021 - DWG AutoCAD 2007/2008/2009
AC1024 - DWG AutoCAD 2010/2011/2012
AC1027 - DWG AutoCAD 2013/2014/2015/2016/2017
AC1032 - DWG AutoCAD 2018/2019/2020/2021/2022/2023/2024
~~~

I believe the DXF file has also the same version scheme.

So, I need to know, that if a user save his drawing to a .dxf file(maybe from some AutoCAD software), which version of DXF do they need to select? Maybe the AC1012? Or maybe a version range from AC1014 to AC1018 is supported?

Thanks.

**EDIT:**

For information:

[DXF (AutoCAD Drawing Interchange Format) Family, ASCII variant](https://www.loc.gov/preservation/digital/formats/fdd/fdd000446.shtml)

[AutoCAD Release History - Between the Lines](https://autodesk.blogs.com/between_the_lines/autocad-release-history.html)

[.dwg - Wikipedia](https://en.wikipedia.org/wiki/.dwg)

**Comment by JamesBremner** [comment]
I have tested the program with AC1009 and AC1015.

I believe the DXF file format is mature and stable, so I doubt there are significant changes between the versions. So anything between and including those version should work, almost certainly.  If possible, please test with any other versions you are able to save to, and let me know the results.

I will add a user option to display the file version.

**Comment by JamesBremner** [comment]
Issue #43 implemented.  Do you still support wxWidgets?  Then you will need to add a call to 

https://github.com/JamesBremner/DXF_Viewer/blob/d9aabc51f187b6b79bc4405897b7c6fbb1ced506/src/Dxf.h#L346

**Comment by asmwarrior** [comment]
> Issue #43 implemented. Do you still support wxWidgets? Then you will need to add a call to
> 
> https://github.com/JamesBremner/DXF_Viewer/blob/d9aabc51f187b6b79bc4405897b7c6fbb1ced506/src/Dxf.h#L346

Thanks, yes, I'm still using wxWidgets ports, so I will make changes to the wxWidgets related code, and maybe I will write a PR soon.

**Comment by asmwarrior** [comment]
[wxWidgets port: add menu item to support reading DXF file version by asmwarrior · Pull Request #44 · JamesBremner/DXF_Viewer](https://github.com/JamesBremner/DXF_Viewer/pull/44)

The PR is created.

**Comment by JamesBremner** [comment]
please test with any other versions you are able to save to, and let me know the results.

**Comment by asmwarrior** [comment]
My client use dxf version AC1027, and the dxf file size is very large,  It always takes several seconds to load the dxf file.

It generally shows well, but I found some issues that when handling the spline, some generated point coordinate value becomes infinity, I will try to reduce the dxf file size and make a minimal sample dxf file.
