### ISSUE TITLE
Wrong line caused by the NaN value in drawing spline

### ISSUE THREAD

**Issue by asmwarrior** [JamesBremner/DXF_Viewer#45]
In some time, I would like to draw all the lines with the line width = 2, so I have such code changes for the wxWidgets port:

~~~
From 2b29e4f562a09a9781fe31df2394998a7f22967e Mon Sep 17 00:00:00 2001
From: asmwarrior <asmwarrior@hiddensite.com>
Date: Thu, 19 Dec 2024 11:42:19 +0800
Subject: [PATCH] test code for the line width = 2

change the linewidth to 2

---
 src/wxWidgets.cpp | 29 +++++++++++++++++++++--------
 1 file changed, 21 insertions(+), 8 deletions(-)

diff --git a/src/wxWidgets.cpp b/src/wxWidgets.cpp
index 4daf3ed..569224e 100644
--- a/src/wxWidgets.cpp
+++ b/src/wxWidgets.cpp
@@ -407,12 +407,13 @@ void CLine::Draw( CDxf* dxf )
 {
     cDrawPrimitiveData draw( dxf );
 
+    int lineWidth = 2;
     // loop over drawing primitives
     while( getDraw( draw ) )
     {
         wxColour c(draw.color);
         theDC->SetBrush(wxBrush(c));
-        theDC->SetPen(wxPen(c));
+        theDC->SetPen(wxPen(c, lineWidth));  // Set line width to 2
         theDC->DrawLine( draw.x1, draw.y1, draw.x2, draw.y2 );
     }
 }
@@ -420,6 +421,7 @@ void CArc::Draw( CDxf* dxf )
 {
     cDrawPrimitiveData draw( dxf );
 
+    int lineWidth = 2;
     // loop over drawing primitives
     while( getDraw( draw ) )
     {
@@ -429,7 +431,7 @@ void CArc::Draw( CDxf* dxf )
         wxColour c(draw.color);
         // Set the brush to be transparent
         theDC->SetBrush(*wxTRANSPARENT_BRUSH);
-        theDC->SetPen(wxPen(c));
+        theDC->SetPen(wxPen(c, lineWidth));  // Set line width to 2
         theDC->DrawEllipticArc (
             xTopLeft, yTopLeft,
             diameter, diameter,
@@ -440,13 +442,14 @@ void CCircle::Draw( CDxf* dxf )
 {
     cDrawPrimitiveData draw( dxf );
 
+    int lineWidth = 2;
     // loop over drawing primitives
     while( getDraw( draw ) )
     {
         wxColour c(draw.color);
         // Set the brush to be transparent
         theDC->SetBrush(*wxTRANSPARENT_BRUSH);
-        theDC->SetPen(wxPen(c));
+        theDC->SetPen(wxPen(c, lineWidth));  // Set line width to 2
         theDC->DrawCircle( draw.x1, draw.y1, draw.r );
     }
 }
@@ -454,12 +457,13 @@ void cLWPolyLine::Draw( CDxf* dxf )
 {
     cDrawPrimitiveData draw( dxf );
 
+    int lineWidth = 2;
     // loop over drawing primitives
     while( getDraw( draw ) )
     {
         wxColour c(draw.color);
         theDC->SetBrush(wxBrush(c));
-        theDC->SetPen(wxPen(c));
+        theDC->SetPen(wxPen(c, lineWidth));  // Set line width to 2
         theDC->DrawLine( draw.x1, draw.y1, draw.x2, draw.y2 );
     }
 }
@@ -467,12 +471,13 @@ void CText::Draw( CDxf* dxf )
 {
     cDrawPrimitiveData draw( dxf );
 
+    int lineWidth = 2;
     // loop over drawing primitives
     while( getDraw( draw ) )
     {
         wxColour c(draw.color);
         theDC->SetBrush(wxBrush(c));
-        theDC->SetPen(wxPen(c));
+        theDC->SetPen(wxPen(c, lineWidth));  // Set line width to 2
         theDC->DrawText( draw.text, draw.x1, draw.y1 );
     }
 }
@@ -481,13 +486,19 @@ void CSpline::Draw( CDxf* dxf )
     wxPoint spline_points[MAXPOINTS];
     cDrawPrimitiveData draw( dxf );
 
+    int lineWidth = 2;
+
     wxColour c(draw.color);
     theDC->SetBrush(wxBrush(c));
-    theDC->SetPen(wxPen(c));
+    theDC->SetPen(wxPen(c, lineWidth));  // Set line width to 2
 
     // loop over drawing primitives
-    while( getDraw( draw ) )
+    while (getDraw(draw))
     {
+//        // Check if any of the values are NaN, if YES, we won't draw anything, try next draw object
+//        if (std::isnan(draw.x1) || std::isnan(draw.y1) || std::isnan(draw.x2) || std::isnan(draw.y2))
+//            continue;
+
         if( dxf->wxwidgets() && m_ControlPointCount>0  )
         {
             // use wxwidgets spline method for control point spline TID6
@@ -511,6 +522,7 @@ void CSpline::Draw( CDxf* dxf )
         {
             // use wxwidgets drawing primitive for spline
 
+            theDC->SetPen(wxPen(c, lineWidth));  // Set line width to 2
             theDC->DrawLine( draw.x1, draw.y1, draw.x2, draw.y2 );
         }
     }
@@ -519,6 +531,7 @@ void CSolid::Draw( CDxf* dxf )
 {
     cDrawPrimitiveData draw( dxf );
 
+    int lineWidth = 2;
     // loop over drawing primitives
     while( getDraw( draw ) )
     {
@@ -535,7 +548,7 @@ void CSolid::Draw( CDxf* dxf )
 
         wxColour c(draw.color);
         theDC->SetBrush(wxBrush(c));
-        theDC->SetPen(wxPen(c));
+        theDC->SetPen(wxPen(c, lineWidth));  // Set line width to 2
 
         theDC->DrawPolygon(3, points);
     }
-- 
2.42.0.windows.2


~~~

With this code changes, it looks like I see one wrong line drawn, see the image shot below:

![image](https://github.com/user-attachments/assets/89a561a1-20b0-4850-9396-1b03ce25bfb9)

If I use the mouse scroll to zoom the plot, another wrong line will shown, see image shot below:

![image](https://github.com/user-attachments/assets/3559c31e-309c-40ee-9586-689e2b8034b1)

The strange thing is that this wrong line only happens in the code what I try to draw with line width = 2, by default, with line width = 1, I do not see the wrong lines.

I debugged it for a lot of time, and finally I found that the `NaN` value when drawing the spline cause this issue, so if I enable such check: (you can see those `isnan` check code in my patch file, but they are commented out for testing.)

~~~
        // Check if any of the values are NaN, if YES, we won't draw anything, try next draw object
        if (std::isnan(draw.x1) || std::isnan(draw.y1) || std::isnan(draw.x2) || std::isnan(draw.y2))
            continue;
~~~

Then those wrong lines will gone, see the image shot below:

![image](https://github.com/user-attachments/assets/c22db64b-8fd4-4ddd-8cb0-a202284c01c0)

So, I believe this is something wrong, but I'm not sure which causes such issue, if I open the sample dxf file in LibreCAD, I don't see the wrong line, but of cause, in LibreCAD, the line width is 1.

I will attach the simplified dxf file as attachment.

[simplify-v1-dxffile.zip](https://github.com/user-attachments/files/18229629/simplify-v1-dxffile.zip)

**Comment by JamesBremner** [comment]
I cannot reproduce this in the windex build.  However, debugger shows that nan values are produced from

https://github.com/JamesBremner/DXF_Viewer/blob/76a9ce6825b2e513c4580ee523ee5d91e49a378d/src/Spline.cpp#L511-L512

Seems that windex swallows the nan values without complaint or ill effect.  This means that I cannot really test any fix - testing is up to you.

In testing I noticed that lines are always drawn with width 1 pixel, no matter what is specified in the DXF file.  I have fixed that for both windex and wxwidgets.  Please test this for wxWidgets - `tid45-2.dxf` should draw lines of width 2.

**Comment by JamesBremner** [comment]
I have made a guess at what should be generated instead of a nan - alpha = 0.5 - i.e. half way between control points.  As far as I can tell, this works.  If you have any better insight, let me know.

Please test.

**Comment by asmwarrior** [comment]
Here is the testing result:

![image](https://github.com/user-attachments/assets/91e84047-fd2e-471c-b600-547ee531f6e7)


You can see that when I open the `tid45-2.dxf` with the width default setting as `2`, I still see the wrong line.

Note that I have to modify the source code with the following patch, because I have set the initial member variable `thick(2)`, if I set it to `1`, I can't see the wrong line, actually the wrong line is from the spline calculation, so in my patch below, all the thick value is set to 2 to reproduce the bug.

~~~
From b9a6d265f4661392840286abffacc79e6719e24a Mon Sep 17 00:00:00 2001
From: asmwarrior <asmwarrior@hiddensite.com>
Date: Thu, 19 Dec 2024 11:42:19 +0800
Subject: [PATCH] test code for the line width = 2

change the linewidth default value to 2 to reproduce the bug

the thick member variable should have initial value, for testing, we set to 2
---
 src/Dxf.cpp       |  1 +
 src/wxWidgets.cpp | 19 ++++++++++++-------
 2 files changed, 13 insertions(+), 7 deletions(-)

diff --git a/src/Dxf.cpp b/src/Dxf.cpp
index 9f72ed5..85683d0 100644
--- a/src/Dxf.cpp
+++ b/src/Dxf.cpp
@@ -252,6 +252,7 @@ namespace dxfv
     }
 
     cDrawPrimitiveData::cDrawPrimitiveData(CDxf *dxf)
+        : thick(2)
     {
         index = 0;
         index_curve = 0;
diff --git a/src/wxWidgets.cpp b/src/wxWidgets.cpp
index d7505d8..d7d9826 100644
--- a/src/wxWidgets.cpp
+++ b/src/wxWidgets.cpp
@@ -412,7 +412,7 @@ void CLine::Draw( CDxf* dxf )
     {
         wxColour c(draw.color);
         theDC->SetBrush(wxBrush(c));
-        theDC->SetPen(wxPen(c),draw.thick);
+        theDC->SetPen(wxPen(c, draw.thick));
         theDC->DrawLine( draw.x1, draw.y1, draw.x2, draw.y2 );
     }
 }
@@ -429,7 +429,7 @@ void CArc::Draw( CDxf* dxf )
         wxColour c(draw.color);
         // Set the brush to be transparent
         theDC->SetBrush(*wxTRANSPARENT_BRUSH);
-        theDC->SetPen(wxPen(c));
+        theDC->SetPen(wxPen(c, draw.thick));
         theDC->DrawEllipticArc (
             xTopLeft, yTopLeft,
             diameter, diameter,
@@ -446,7 +446,7 @@ void CCircle::Draw( CDxf* dxf )
         wxColour c(draw.color);
         // Set the brush to be transparent
         theDC->SetBrush(*wxTRANSPARENT_BRUSH);
-        theDC->SetPen(wxPen(c));
+        theDC->SetPen(wxPen(c, draw.thick));
         theDC->DrawCircle( draw.x1, draw.y1, draw.r );
     }
 }
@@ -459,7 +459,7 @@ void cLWPolyLine::Draw( CDxf* dxf )
     {
         wxColour c(draw.color);
         theDC->SetBrush(wxBrush(c));
-        theDC->SetPen(wxPen(c));
+        theDC->SetPen(wxPen(c, draw.thick));
         theDC->DrawLine( draw.x1, draw.y1, draw.x2, draw.y2 );
     }
 }
@@ -472,7 +472,7 @@ void CText::Draw( CDxf* dxf )
     {
         wxColour c(draw.color);
         theDC->SetBrush(wxBrush(c));
-        theDC->SetPen(wxPen(c));
+        theDC->SetPen(wxPen(c, draw.thick));
         theDC->DrawText( draw.text, draw.x1, draw.y1 );
     }
 }
@@ -483,11 +483,15 @@ void CSpline::Draw( CDxf* dxf )
 
     wxColour c(draw.color);
     theDC->SetBrush(wxBrush(c));
-    theDC->SetPen(wxPen(c));
+    theDC->SetPen(wxPen(c, draw.thick));
 
     // loop over drawing primitives
     while( getDraw( draw ) )
     {
+//        // Check if any of the values are NaN, if YES, we won't draw anything, try next draw object
+//        if (std::isnan(draw.x1) || std::isnan(draw.y1) || std::isnan(draw.x2) || std::isnan(draw.y2))
+//            continue;
+
         if( dxf->wxwidgets() && m_ControlPointCount>0  )
         {
             // use wxwidgets spline method for control point spline TID6
@@ -511,6 +515,7 @@ void CSpline::Draw( CDxf* dxf )
         {
             // use wxwidgets drawing primitive for spline
 
+            theDC->SetPen(wxPen(c, draw.thick));
             theDC->DrawLine( draw.x1, draw.y1, draw.x2, draw.y2 );
         }
     }
@@ -535,7 +540,7 @@ void CSolid::Draw( CDxf* dxf )
 
         wxColour c(draw.color);
         theDC->SetBrush(wxBrush(c));
-        theDC->SetPen(wxPen(c));
+        theDC->SetPen(wxPen(c, draw.thick));
 
         theDC->DrawPolygon(3, points);
     }
-- 
2.42.0.windows.2

~~~

**Comment by JamesBremner** [comment]
Please test with the code I posted, unaltered.  If you use tid45-2, the lines are specified as 2 pixels wide with NO NEED TO ALTER the code.

![image](https://github.com/user-attachments/assets/ec5dbca4-5b76-4d52-8c2d-e1f053e16d08)

**Comment by asmwarrior** [comment]
> Please test with the code I posted, unaltered. If you use tid45-2, the lines are specified as 2 pixels wide with NO NEED TO ALTER the code.
> 

Hi, when I tested with your github master branch code, I at least need to change like below to fix the build error.

~~~
diff --git a/src/wxWidgets.cpp b/src/wxWidgets.cpp
index d7505d8..d7d9826 100644
--- a/src/wxWidgets.cpp
+++ b/src/wxWidgets.cpp
@@ -412,7 +412,7 @@ void CLine::Draw( CDxf* dxf )
     {
         wxColour c(draw.color);
         theDC->SetBrush(wxBrush(c));
-        theDC->SetPen(wxPen(c),draw.thick);
+        theDC->SetPen(wxPen(c, draw.thick));
         theDC->DrawLine( draw.x1, draw.y1, draw.x2, draw.y2 );
     }
 }
~~~

While, in the above code, you only apply the "draw.thick" to the "CLine::Draw", not the other kinds of graphics.  

But the bug I reported is that 

**the "NaN points" happens inside the "Spline" components, and when I try to draw the spline with the line width == 2.** 

If you look the dxf's contents, there is no default thick setting for the spline, ideally the default thick setting should be 1, but that does not expose the bug, so I have to set the default thick value to `2`.

So, with the following patch, I can tweak the spline width setting.
~~~
@@ -483,11 +483,15 @@ void CSpline::Draw( CDxf* dxf )
 
     wxColour c(draw.color);
     theDC->SetBrush(wxBrush(c));
-    theDC->SetPen(wxPen(c));
+    theDC->SetPen(wxPen(c, draw.thick));
 
     // loop over drawing primitives
     while( getDraw( draw ) )
     {
+//        // Check if any of the values are NaN, if YES, we won't draw anything, try next draw object
+//        if (std::isnan(draw.x1) || std::isnan(draw.y1) || std::isnan(draw.x2) || std::isnan(draw.y2))
+//            continue;
+
         if( dxf->wxwidgets() && m_ControlPointCount>0  )
         {
             // use wxwidgets spline method for control point spline TID6
@@ -511,6 +515,7 @@ void CSpline::Draw( CDxf* dxf )
         {
             // use wxwidgets drawing primitive for spline
 
+            theDC->SetPen(wxPen(c, draw.thick));
             theDC->DrawLine( draw.x1, draw.y1, draw.x2, draw.y2 );
         }
     }
@@ -535,7 +540,7 @@ void CSolid::Draw( CDxf* dxf )
 
         wxColour c(draw.color);
         theDC->SetBrush(wxBrush(c));
-        theDC->SetPen(wxPen(c));
+        theDC->SetPen(wxPen(c, draw.thick));
 
         theDC->DrawPolygon(3, points);
     }
-- 
~~~
**Note: the bug only happens when I draw the spline with the thick == 2. It shows correctly when the spline's thick == 1.**


But either the "tid45.dxf" or "tid45-2.dxf" does not have the spline thick value == 2. It only has the "Line thick == 1"
So to expose this bug, I have to manually set the "thick == 2" for all the components, thus you can see some wrong lines were drawn.

I hope you can understand the logic.

**Comment by JamesBremner** [comment]
With the spline thickness option implemented in #46 I can now reproduce this.

![image](https://github.com/user-attachments/assets/2ab9a8f9-a378-40c0-9f2f-a49f8ddf57f2)

**Comment by JamesBremner** [comment]
The problem seems to be here

https://github.com/JamesBremner/DXF_Viewer/blob/845ba4c0b61840bd6aef9e2dfa40785c579954f3/src/Spline.cpp#L517-L521

The first time through j1 = 0, k = 0, degree = 3

so the c index is out of bounds and picking up garbage values.

**Comment by JamesBremner** [comment]
As a quick fix I will clamp the index to >= 0

The result of doing so looks acceptable

![image](https://github.com/user-attachments/assets/2a9c638a-b850-476d-9c24-c9ecee5b5879)

**Comment by JamesBremner** [comment]
After the holiday, I will take another look at this code and attempt to find a more meaningful fix.

In the meantime, this should give you decent results.

**Comment by JamesBremner** [comment]
Found the problem.

The knot values must be in the range 0 to 1, with 0 being the start of the spline curve and 1 the end of the curve.

The code that is supposed to ensure the knot values are in the expected range is incorrect..

https://github.com/JamesBremner/DXF_Viewer/blob/813f256936093cf77d8d388f3b2ac392dd7a9582/src/Spline.cpp#L285

**Comment by asmwarrior** [comment]
> Found the problem.
> 
> The knot values must be in the range 0 to 1, with 0 being the start of the spline curve and 1 the end of the curve.
> 
> The code that is supposed to ensure the knot values are in the expected range is incorrect..
> 
> https://github.com/JamesBremner/DXF_Viewer/blob/813f256936093cf77d8d388f3b2ac392dd7a9582/src/Spline.cpp#L285

Hi, James, thanks.

In-fact, I'm not familiar with this algorithm, so I can only test it. I will test the latest code today.

**Comment by asmwarrior** [comment]
> I will test the latest code today.

I just tested it, and I don't see the ugly lines. I tested the tid45.dxf, tid45-2.dxf, tid46.dxf, it works OK under the wxWidgets ports.

**Comment by JamesBremner** [comment]
Sounds good.  Close?

**Comment by asmwarrior** [comment]
Ok, I will close it.
