### ISSUE TITLE
Some arrays' length are hard-coded

### ISSUE THREAD

**Issue by asmwarrior** [JamesBremner/DXF_Viewer#5]
In such code snippet:
```
class CSpline  : public cDXFGraphObject
{
public:
	std::string m_Layer;
	int m_FitPointCount;
	int m_ControlPointCount;
	double x[128],y[128];
```
So, we should make it a std::vector<double>, otherwise, we will not handling spline which length are more than 128 points.

**Comment by asmwarrior** [comment]
I see another place which has some fixed array length: PolyLine.h, which has `double x[1024],y[1024];`

**Comment by JamesBremner** [comment]
https://github.com/JamesBremner/DXF_Viewer/blob/3422cfd9c61c8b6b70bc10df120dda05cf200416/src/Spline.h#L14

**Comment by JamesBremner** [comment]
> I see another place ...

Please open a separate issue.

Please test this and close if it works. ( That what the label **test** means )

**Comment by asmwarrior** [comment]
I see an crash issue when loading a dxf file at this commit: [Compiler option to increase spline point maximum](https://github.com/JamesBremner/DXF_Viewer/commit/3422cfd9c61c8b6b70bc10df120dda05cf200416), so I will debug which change cause this crash issue.

I will open another issue about the hard-coded array length in PolyLine.h.
Thanks

**Comment by asmwarrior** [comment]
I think I can close this issue, and I have create another issue about the hard-coded array length in another class.
