### ISSUE TITLE
Add option to use wxwidgets DrawSpline method

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/DXF_Viewer#6]
Requested in #2 

https://docs.wxwidgets.org/3.0/classwx_d_c.html#ad72d38c75ac6b3f80c1f957dd94089fa

**Comment by asmwarrior** [comment]
I see some dxf files have splines which have both control points and fit points. I try to find some document or reference. But strange, I can't find any. Can you have some idea that we can support this kinds of spline. I see spline have either control points or fit points are already supported. But when both kinds of points exits, the program just throw an exception and exits.

Thanks.

**Comment by JamesBremner** [comment]
> But when both kinds of points exits, the program just throw an exception and exits.

This is the intended behavior.

>  I see spline have either control points or fit points are already supported

OK.  Closing.
